name: Feature Request
description: 新しい機能の提案を作成します。
title: "feat: "
labels:
  - "feature"

body:
  - type: textarea
    id: description
    attributes:
      label: 概要
      description: どのような機能を提案しますか？
      placeholder: 機能の概要について
